export const GET_PRODUCTS_DETAILS_REQUEST = "GET_PRODUCTS_DETAILS_REQUEST";
export const GET_PRODUCTS_DETAILS_SUCCESS = "GET_PRODUCTS_DETAILS_SUCCESS";
export const GET_PRODUCTS_DETAILS_FAILURE = "GET_PRODUCTS_DETAILS_FAILURE";
